### ISSUE TITLE
Divide up pdom elements into play area and control area

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-data-lab#107]
Starting at https://github.com/phetsims/projectile-data-lab/issues/64#issuecomment-1912310230

@matthew-blackman said:

> @jessegreenberg and @terracoda - @samreid and I noticed that we were only using the pdomControlAreaNode, and were wondering if we should be splitting things up between that and that pdomPlayAreaNode. It did seem more flexible to put everything in a single parent since we can easily change the order, but we may not be considering all needs here. Can you weigh in?

**Comment by samreid** [comment]
@terracoda replied:

Great question about pdomPlayAreaNode  and pdomControlAreaNode.

For long term accessibility and consistency across all sims, you should be using both.

You want your essential interactions to be in the pdomPlayAreaNode, and anything secondary or tertiary in the pdomControlAreaNode.

Those decision are not always easy to make, especially when there are many controls, like there are in this sim, but you want to think about what interactions are truly essential for the main learning goals:

1. The launcher and the field are essential
2. The histogram and the launcher projectile confirmations are likely pretty essential.
3. The tape measure, timer and view tools are very likely best in the Control Area.

Everything in the Play Are comes before the Control Area in the Tab order.

**Comment by samreid** [comment]
@jessegreenberg said:

> +1 for what @terracoda said. Assigning contents to the different parents can categorize page content nicely under "Play Area" and "Control Area" headings in the Parallel DOM for a screen reader user. Using both will have no impact on alt input (other than that play area contents come before the control area contents).

**Comment by samreid** [comment]
So what parts of this simulation would be in the "play area"?

**Comment by samreid** [comment]
@jessegreenberg replied:

The things that are most important to the pedagogy/interaction should go in the play area. Sometimes it has been everything except the "Reset All" button. 

Here is how some other sims have divvied it up:
https://github.com/phetsims/gravity-force-lab/blob/7ae7430c16eac840d2c2d24de62772bec466bc8f/js/view/GravityForceLabScreenView.js#L264-L276

https://github.com/phetsims/ratio-and-proportion/blob/b20713b13f371ba5771cedfb21cbac39fcf13c9e/js/common/view/RAPScreenView.ts#L463-L472

https://github.com/phetsims/greenhouse-effect/blob/47967c6759a1f691004ce17c0cf9a1c9f322b357/js/common/view/GreenhouseEffectScreenView.ts#L142-L151

**Comment by samreid** [comment]
Keep in mind the overall keyboard order has been designed in https://github.com/phetsims/projectile-data-lab/issues/64 and should not be changed lightly for this issue.

**Comment by samreid** [comment]
Based on the recommendations above, it seems the control panels in the top right in and the reset all button should be in the control area.  However, this raises 2 queustions:

1. Can we change the navigation order so that the field sign/selector comes at the end of the play area, before the control panel, so it can be part of the "play area"?
2. What should be done about the measuring tape checkbox + measuring tape itself? It seems the measuring tape should be in the play area, but the measuring tape checkbox should be in the control panel, but it also seems that after you check the measuring tape checkbox, then tab navigate forward, you should find the measuring tape.

@terracoda can you please recommend how to proceed, or we can meet up over zoom at your discretion.

**Comment by terracoda** [comment]
Re question 1, I think you should try the field sign/selector at the end of the Play Area.

Re question 2, I was wondering why the Tape Measure has to be enabled via a checkbox? Is that really necessary? Have you explored other ideas?

**Comment by kathy-phet** [comment]
@samreid @terracoda - The alt-input pattern with the Measuring Tape and Timer nodes in My Solar System and Kepler's Laws were designed for this similar interaction, so you can look at that flow and implementation which MM, EM, MK, AV worked on. It puts the timer and measuring tape into the play area. My understanding of the design approach was once you add it its located where you want it to be convenient for interacting with the other things in the play area, but the check box is in the control area because its an added tool, but not something you want to be navigating too all the time while in the play area.

**Comment by samreid** [comment]
Thanks, I incorporated the feedback in the commit. I think it will work even better once https://github.com/phetsims/projectile-data-lab/issues/104 is complete.

> Re question 2, I was wondering why the Tape Measure has to be enabled via a checkbox? Is that really necessary? Have you explored other ideas?

We have not discussed other ways to enable/disable the tape measure. Following the precedent @kathy-phet described sounds reasonable to me.

Otherwise, this issue is ready for review.

**Comment by samreid** [comment]
Thanks @terracoda. The simulation currently looks like this:

![image](https://github.com/phetsims/projectile-data-lab/assets/679486/7f6a6d10-cb7e-48e8-bae3-fb8270333644)

> I agree the enabled checkbox should go in the Play Area, in a useful spot, not sure where that would be.

I can't tell if you are recommending to change the visual layout or just what is in playArea/controlArea.  Right now the order is like this:

```ts
    this.pdomPlayAreaNode.pdomOrder = [

      // Launch controls
      this.launchButton,
      this.singleOrContinuousRadioButtonGroup,

      // Play area tools
      this.measuringTapeNode,
      this.stopwatchNode,
      ...( intervalToolNode ? [ intervalToolNode ] : [] ),

      // Projectile selector
      this.projectileSelectorNode
    ];

    this.pdomControlAreaNode.pdomOrder = [

      // Experiment setup
      this.launchPanel,

      // Field management
      this.fieldRadioButtonGroup,
      this.eraserButton,

      // Histogram
      this.accordionBox,

      // Global tools
      staticToolPanel,
      interactiveToolPanel,
      this.timeControlNode,

      // Reset all
      this.resetAllButton
    ];
```

**Comment by matthew-blackman** [comment]
In the 2/8 design meeting, this was reviewed and it was recommended that all controls should be in the play area except for the global controls.

**Comment by samreid** [comment]
I committed updates that I understood to be the recommendation from the 2/8 design meeting.

**Comment by kathy-phet** [comment]
@matthew-blackman @samreid: I took a quick look here and this is the current order (as seen in the a11y view): 

**> play area:** 
> fire button
> fire single/continuous
> projectile configuration
> histogram 
> data point inspector (not sure what we are calling this)
> fields
> field erase
> (measuring tape adds here) 
> (timer adds here)
> 
**> control area:** 
> rt hand check boxes
> timer control 
> reset all 

I see why "fire" is placed first, but I might consider a somewhat different order for the following reasons. The goal would be to keep the "play area conceptual flow of "set the laucher/configuration" -> then fire -> then go inspect the histogram (reorganizing and such); then back up choose a different launcher/configuration and then work on launching and understanding that data. So keeping launch and histogram close seems to make sense to me in the flow of investigation. Then adding measuring tape and timer right after the fire controls seems logical because you would "fire" then "measure" then "fire" then "measure". (The current order that inserts the projectile configuration between fire and histogram interrupts looking at the data you just took in my mind of the play flow). 

**play area:** 
projectile configuration
fire button
fire single/continuous
(measuring tape adds here) 
(timer adds here)
histogram 
data point inspector (not sure what we are calling this)
fields
field erase

**control area:** 
rt hand check boxes
timer control 
reset all 

Github is probably not the best mechanism to iterate on this. Happy to join a design meeting to iterate.

**Comment by terracoda** [comment]
Some thoughts unrelated to the main issue:

1. There are so many Tab Stops in this sim, I am wondering if a little more grouping could make things a whole lot more efficient - like making the visually grouped checkboxes, each a group of checkboxes. that would reduce 5 Tab Stops to 2 Tab Stops. If that is possible with common code, I'd do that.
2. Timing Controls - I would like to explore at a convenient time if we can have an option to make this complex control a meaningful single group. We have hot keys to get a Pause/Play button so that's easily accessible regardless of grouping. Grouping would reduce Tab Stops, here too.

Will come back to this shortly. What KP is proposing seems great. I just haven;t explore fully yet.

**Comment by kathy-phet** [comment]
Thanks, Taliesin. Can you please make these 2 ideas into their own issues and add to the Monday planning board for alt-input for priority evaluation? Tag them and they should add automatically. We are working through that list so these should be evaluated as part of that since they would each need resources and investment in common code.  Thanks. Sent from my iPhoneOn Feb 14, 2024, at 7:27 AM, Taliesin L. Smith ***@***.***> wrote:﻿
Some thoughts unrelated to the main issue:

There are so many Tab Stops in this sim, I am wondering if a little more grouping could make things a whole lot more efficient - like making the visually grouped checkboxes, each a group of checkboxes. that would reduce 5 Tab Stops to 2 Tab Stops. If that is possible with common code, I'd do that.
Timing Controls - I would like to explore at a convenient time if we can have an option to make this complex control a meaningful single group. We have hot keys to get a Pause/Play button so that's easily accessible regardless of grouping. Grouping would reduce Tab Stops, here too.

Will come back to this shortly. What KP is proposing seems great. I just haven;t explore fully yet.

**Comment by terracoda** [comment]
I have to push back on keeping the Launcher button first in the Tab order.

A learner needs to launch something to make any sense at all in this sim. Playing with configuration seems very important but secondary to launching, assuming that the initial configuration is in itself a pedagogically meaningful configuration.

Also, if zoomed in on configuration on a small device, a learner may not see the launch button or the configuration options.

The histogram as-is, is actually 5 Tab Stops. Kathy's outline doesn't take this into account. There would be be 4 more Tab Stops in between the histogram collapse/expand button and the data point navigator, if one takes into account the controls within the histogram display.

**Question:** Is it important to explore the histogram displayed data and the field data right next to each other?

If so, we should have a shortcut to the histogram - that might solve the issue of non-contiguity of the data displays (histogram and field). If an additional shortcut seems reasonable, the design team should consider if a pair of data-reading shortcuts (i.e., important data exploration points) would be useful. We already have a shortcut for the Launcher, so it's easy to stay on the histogram and launch more data and then re-explore the histogram data or stay on the data navigator and launch more data.

I suggest the following linear exploration order. I put questions, context, and consideration in [[square brackets]]:

**Play Area:**
Launcher, button (1 Tab Stop)
Launcher Configurations, radio group (1 Tab Stop) [[Would a button work, see more below?]]
(Measuring Tape, when enabled) (2 Tab Stops)
- (Start of Tape)
- (End of Tape)
(Stop Watch Launcher, button when enabled) (1 Tab Stop)
Histogram (5 Tab Stops) 
- Histogram expand/collapse, button
- Zoom out, button
- Zoom in, button
- Bin Width, combobox
- Bars/No Bars, switch  
Launcher Configurations (3 Tab Stops) 
- Launcher Angle
- Projectiles
- Mystery Launcher  
Field {{1}} Data Point Selector/Navigator (1 Tab Stop) [[Works like a number spinner. Consider a shortcut if this control needs easy access for all.]] 
Field {{1}} (1 Tab Stop) [[Works like a radio group. We have a number shortcut to easily compare non-contiguous fields.]]
Erase Field Data, button (1 Tab Stop) [[Works like a partial-reset button. Nicely placed next to fields.]]

**Control Area:**
Checkboxes (5 Tab Stops)
- Paths [[Navigable with Field Data Selector]]
- Launch Angle [[Navigable with Field Data Selector]]
- Launch Speed [[Is this control only relevant when launching? I am not sure what this visual tool does.]]
- Measuring Tape [[Adds/removes a visual Tape Measure.]]
- Stop Watch [[Adds/removes a visual Stop Watch with Launcher button.]]
Timing Controls (2 Tab Stops)
- Pause/Play, button
- Sim Speeds, radio group: Normal, Slow
Reset All, button (1 Tab Stop)


**OTHER THOUGHTS:**
For the Launcher button, you might want to consider having two buttons and avoid using the radio buttons. You could even consider having a single button with a Press/Hold option to fire continuously. For keyboard users, button interactions provide that functionality out of the box with the Space and Enter keys. Space provides a single fire on the up event, and Enter provides a continuous fire on the down event. That's just how buttons work. So for pointer/mouse a single button with a press and hold option that does continuous launching until released might be a nice button option.

**Comment by terracoda** [comment]
Each bullet point above is a potential Tab Stop - for a total of 16 Tab Stops when Tape Measure and Stop Watch are enabled.

**Comment by terracoda** [comment]
I don't know what is more important - checking the histogram or changing the launcher configurations. If a learner is first expected to play, I think the configurations radiogroups  should come before the histogram display.

I am going to update the above.

I think a shortcut, or a pair of shortcuts could address the data navigation issues.

**Comment by terracoda** [comment]
I think I circled back to something close to the original, except @kathy-phet 's placement of the enabled Tape Measure and Stop Watch is better. They should be closer to the Launcher/Launch button.

**Comment by terracoda** [comment]
From Slack:

> Sorry, for the delay. I had to fix my comment several times to get it consistently laid out. I think KP’s placement of the Tap Measure and Stop Watch are better, but I still think the Launcher controls and the Launcher Configurations should come first. They encourage play before analysis. Once a leaner is in analysis mode, they can potentially use shortcuts to quickly get to the data displays.

I hope this is helpful. As @kathy-phet said, we should have a meeting if more discussion is needed.

**Comment by kathy-phet** [comment]
Happy to go with Taliesin's proposal, but if there is opportunity to get feedback from keyboard users in the future, I would be curious about their preferred order, because I still feel like the "flow" once you know what the sim has available makes more sense putting the launch configuration first because conceptually having it interrupt the launch data <-> visit histogram closeness seems distracting to the investigation/experimentation order. 

I'm also happy to join for "in-person" meeting if @matthew-blackman wants to discuss more. 

If we do meet, we could also discuss if a "launch projectile" button press keyboard short-cut would be something desirable for this sim.

**Comment by matthew-blackman** [comment]
An in-person meeting sounds good. I'll put it on the agenda for design meeting and see that @terracoda is added to the invite. Looking forward to it!

**Comment by terracoda** [comment]
We had an in-person design meeting. I respect the design team's decision to put the launcher after the 3 configuration radio button groups. The design team has pedagogical expertise that I do not. 

That said, I would like to document my perspective on the interaction flow...

With a launcher shortcut in place, a learner can launch more data with their keyboard focus on either the histogram or the configurations. The 4 intermediate Tab Stops (3 configuration radio groups and 1 launcher radio group) between the histogram and launcher are easily avoided and would not be "in the way of the data."

Placing the 3 configuration radio button groups after the launcher puts them next to the data displayed in the histogram, so a learner can easily check configurations alongside the data that has been launched or is to be launched using the shortcut.

I do think interviews with learners who use the keyboard would be quite enlightening here, especially for a sim with this many interactions. Please let me know if I can be of assistance with interviews. I think I have at least two people I can reach out to.

Un-assigning myself for now.

**Comment by pixelzoom** [comment]
In "tour of the sim" meeting on Monday 2/26, @Nancy-Salpepi noted that there's a `pdomOrder` problem for the control area in the Sampling screen.  The field display and `eraserButton` are coming _after_ `resetAllButton`, when `resetAllButton` should be last.  That's because those elements are missing from this code in SamplingScreenView.ts, and are therefore occurring in the default order (the order they were added to scenery).

```ts
    this.pdomControlAreaNode.pdomOrder = [

      // Global controls
      this.timeControlNode,

      // Reset all
      this.resetAllButton
    ];
```

**Comment by samreid** [comment]
I fixed the navigation order for the sampleSelectorNode and eraserButton on the sampling screen.

**Comment by matthew-blackman** [comment]
During the 3/7 design meeting, the design team discussed this with @terracoda and reached the following decisions:

- The keyboard tabbing flow should be 'Set up experiment' -> 'Run experiment' -> 'Analyze data' -> 'Manage data sets' -> 'Global controls'
- The stopwatch and measuring tape should come after the launch controls
- The field sign should come after the measuring tape, so that users can highlight and measure data.
- The histogram should come after the field sign, with the sonification button first in its internal sequence.
- The field selector can come after the histogram, followed by the erase button
- The erase button should be more associated with the field selector.
  - This will require a discussion of how to treat the Sampling screen

**Comment by terracoda** [comment]
**Questions I have:**

1. **Launcher:**  Is it safe to assume the "Launcher" button's name will be "Launcher"? I think it is a good name. The name will influence names of other controls down the road.
3. **Stop Watch:** Why does the Stop Watch have 2 tab stops? Is it possible to get away with one? It still moves with the arrow keys even if focus is on the Stop Watch Launch button.
4. **The Field Sign:** It currently displays "Field {1}". Would a better sign name be: "Field {1} Data" or "Launched Data - Filed {1}". I see this an eventual reading block (Voicing) or a subheading in the PDOM (Interactive Description). The data is interactively navigated (not changed) via a number-spinner-type interaction, which might be represented with the following data points: "LaunchDistance, ProjectileType, LaunchNum of TotalLaunches," which might sound like, "41.4 meters, cannon ball, 5 of 10". I am not sure of order or desired details for the data points.
5. **Launch Angle, display:** The displayed launch angle value doesn't change when I navigate the launched data. Is it supposed to? If not, perhaps the checkbox's name should be named "Last Launch Angle" or "Launch Angle Display"? How is someone supposed to examine a specific Launch Angle with Alt Input and are they supposed to?
6. **Launch Speed, display:** Same question as for the Launch Angle Display.

**Comment by samreid** [comment]
> Launcher: Is it safe to assume the "Launcher" button's name will be "Launcher"? I think it is a good name. The name will influence names of other controls down the road.

@matthew-blackman and I discussed that it will probably be called the "Launch Button"

> Stop Watch: Why does the Stop Watch have 2 tab stops? Is it possible to get away with one? It still moves with the arrow keys even if focus is on the Stop Watch Launch button.

@matthew-blackman and I discussed that there is a separate stop for "just dragging" and a different place for the button.

> The Field Sign: It currently displays "Field {1}". Would a better sign name be: "Field {1} Data" or "Launched Data - Filed {1}".

@matthew-blackman and I discussed that the field sign title was carefully designed over many iterations and we would prefer not to make it more wordy than necessary. The title is meant to indicate the location of the field as well as the data on that field. It also defaults to saying "no data" so that helps communicates that it is where the data will go.

> Launch Angle, display: The displayed launch angle value doesn't change when I navigate the launched data. Is it supposed to? If not, perhaps the checkbox's name should be named "Last Launch Angle" or "Launch Angle Display"? How is someone supposed to examine a specific Launch Angle with Alt Input and are they supposed to?
Launch Speed, display: Same question as for the Launch Angle Display.

Great idea! We will investigate that in a new issue, see https://github.com/phetsims/projectile-data-lab/issues/246

@terracoda does this sound good to you? Please close the issue if so.

**Comment by terracoda** [comment]
**Question 1:**
Sorry, but "Launch Button" is not a good name. It breaks an established design pattern.

In web accessibility, accessible names are separate from the role of the control (i.e., "button" is a role). The role is spoken automatically by assistive technology, so you would hear, "Launch Button, button" - not a good experience for a screen reader user, though quite likely a common one.

Also, I would argue that the word "button" adds redundant visual information. If it looks like a button, is coded as a button, you don't need to call it a button as it will already be understood to be a button in the visual and non-visual experience.

The reason I asked is that "Launcher" and "Launch" (on the Stop Watch) are very similar. Maybe "Remote Launch" or "Remote Launcher" would work on the Stop Watch?

**Question 2:**
Two Tab Stops is fine. It is a group control. If you do interviews with keyboard users, this will something to watch for.

**Question 3:**
Let's discuss so I am clear on what the sign and the control are communicating together.

**Comment by samreid** [comment]
@terracoda @matthew-blackman and I discussed the above topics.

The Launch naming will be designed when we implement description.
The 2 tab stops are good.
The sign and the control are discussed in another issue.

We added innerContent to the launch button in the commit.

Closing.
