### ISSUE TITLE
Lines are looking awkward

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-data-lab#111]
![image](https://github.com/phetsims/projectile-data-lab/assets/679486/abb36249-910a-40b5-9e92-62816ba2b545)

**Comment by samreid** [comment]
This appears to be an aliasing "screen door" effect. I can reproduce it somewhat on mac firefox while reshaping the window, but when I let go of the edge of the window, it re-renders and the problem goes away. I do not see this effect on mac chrome.  @matthew-blackman or @catherinecarter can you help investigate the cause of this?

**Comment by matthew-blackman** [comment]
@samreid and I investigated this and found that the issue was that the major grid line spacing was not a multiple of the minor grid line spacing for a bin width of 2. We fixed the issue by changing the major grid line spacing from 5 to 10, which also made the histogram consistent with the lines on the field. Nice work! Closing.
