### ISSUE TITLE
Sampling Histogram - instrument the thumbnails as a group and individually so clients can hide irrelevant sample sizes or the whole thing

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-data-lab#123]
From #30, we would like to:

* Sampling Histogram - instrument the thumbnails as a group and individually so clients can hide irrelevant sample sizes or the whole thing

**Comment by samreid** [comment]
I implemented this in the commit. The accordion box didn't resize when all were hidden, so it left a blank spot:

![image](https://github.com/phetsims/projectile-data-lab/assets/679486/6b977016-6674-4b87-b78c-065a2d5ae5ce)

Should we work on that?

Also I wasn't 100% sure what tandems to use. Right now it is:

thumbnailContainerNode.visibleProperty
thumbnailContainerNode.sample2ThumbnailNode.visibleProperty

etc.

**Comment by matthew-blackman** [comment]
@samreid and I removed an unused ManualConstraint in SamplingScreenView, which caused the Sampling histogram to collapse nicely when the thumbnails are hidden. We decided not to update the position of the TimeControlNode in this case, since it looked better when it stays aligned with the right side of the screen. Everything is looking great here. Nice work! Closing.
