### ISSUE TITLE
Angle stabilizer should go 'wide' to 'narrow'

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#148]
For the angle stabilizer control, it seems to make more sense to have 'wide' on the left and 'narrow on the right. This would improve the U for the following reasons:

- Moving the slider to the right means “more angle stabilizing”
- Right is higher pitch sound
- "Righty-tighty, lefty-loosey"

Let's implement this!

**Comment by samreid** [comment]
After the commit, the angle stabilizer now goes from wide on the left to narrow on the right. It works well in the simulation. I wired it up through an intermediary bidirectional MappedProperty. I wanted to introduce `angleStabilizationProperty` into the model, but it was complex since it is through the double-layered DynamicProperty. Should we collaborate on that?

**Comment by samreid** [comment]
@matthew-blackman and I reviewed and addressed the recommendation from the prior comment. Closing.
