### ISSUE TITLE
Data measures overlay overlaps with field sign for large projectile distances

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#159]
It was discovered that the data measures overlay can occlude the field sign for large distances. To reproduce this, launch pumpkins from launcher 3 and click 'Standard deviation' and 'Values'.

<img width="476" alt="Screen Shot 2024-02-13 at 12 14 41 PM" src="https://github.com/phetsims/projectile-data-lab/assets/108756567/9889689f-f61f-48de-b089-238627cfa751">

@ariel-phet and I mocked up some ideas on how this can be fixed. We considered a combination of the following:

1. Moving the mean value panel below the mean indicator
2. Shrinking the mean indicator slightly
3. Moving the SD arrows and values down, closer to the mean indicator.
4. Raising the field sign and extending its legs
5. Moving the field sign to the right
6. Adding a semi-transparent backdrop to the data measures overlay, specifically the SD values

Here is a (very) rough mockup that we came up with in our initial discussion.

<img width="369" alt="Screen Shot 2024-02-13 at 12 18 23 PM" src="https://github.com/phetsims/projectile-data-lab/assets/108756567/44cfb607-1424-41d8-a514-b0e134061e5e">

Let's find a balance between fixing this issue without totally overhauling the aspects of the sim design that are working well. @catherinecarter and @arouinfar can you weigh in on how you feel about solutions 1-6 above, and any others we can consider?

**Comment by catherinecarter** [comment]
Before I weigh in about a suggestion given above, let's also consider that the interval tool also occludes the field sign: 
![image](https://github.com/phetsims/projectile-data-lab/assets/109630002/24fc9a0a-249e-45cc-8974-fa207096ee54)

**Comment by catherinecarter** [comment]
**I like the idea of**
- single post holding the sign up 
- raising the sign a bit
- moving the sign to the right.

**I'm on the fence about**
- mean triangle getting much smaller - currently it is matching the size of the Sampling screen mean triangle
- I'm ok making it a little smaller, but I feel like consistency is something to consider

**I'm not a big fan of the mean readout being under the mean for two reasons** 
- it looks awkwardly squished between the bottom edge of the field and the triangle
- it would be inconsistent with the location of the mean readout on the Sampling screen, forcing users to 'find' it again between screens.

**Questions**
- How high can the sign go before it interferes with other things on the screen? 
- Alternatively, could the mean and SD readouts go below the launcher icon and above the "3 of 3?" That might look weird, but I have to ask :)
- The SD is the only readout not encased in an oval-ish white rectangle. What happens if we make all of those readouts be in rounded rectangles and make them match, in whatever capacity that means?

**Comment by catherinecarter** [comment]
@matthew-blackman - yes, I thought of that, too. The interval tool is much less of a concern for me as well. My previous comments were solely for the non-draggable components like the field sign and the data measures.

**Comment by matthew-blackman** [comment]
We reached a healthy compromise here by making  adjustments to the field sign and data measures overlay as described above. Now in cases where the standard deviation text overlaps the field sign, all text and UI is still fully visible and readable. @catherinecarter mentioned that the data measures overlay is a bit cramped now, and we adjusted its sizing to make improvements within the constraints we have. I would consider this issue closed. If ideas for further improvements come up please reopen.
