### ISSUE TITLE
model.md: Does it adequately describe the model, in terms appropriate for teachers? Has it been reviewed by the sim designer?

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-data-lab#184]
https://github.com/phetsims/projectile-data-lab/blob/main/doc/model.md

**Comment by pixelzoom** [comment]
I read through model.md for code review #32, and it looks good to me.  The sim designer typically has sign off, and that would be @matthew-blackman. 

Reminder that model.md is linked into the PhET-iO deliverables (in the wrapper index?). So in addition to teachers, the audience is PhET-iO clients (instructional designers, developers, ...)

**Comment by pixelzoom** [comment]
Since this sim is now in RC testings, should this issue be closed?

**Comment by matthew-blackman** [comment]
The model.md file has been updated and reviewed. Labeling for cherry-pick.

**Comment by arouinfar** [comment]
@matthew-blackman related to #299, projectile-sampling-distribution will also need a model.md file. It can be a placeholder that points to projectile-data-lab's model.md. For example: https://github.com/phetsims/concentration/blob/main/doc/model.md

Without this placeholder, there will be a broken link in phet-io-guide.md because it points to sim-name's model.md.

**Comment by KatieWoe** [comment]
Looks good in rc.2
