### ISSUE TITLE
Are sounds added to the correct categoryName? 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/projectile-data-lab#228]
For code review #32 ...

There are 30 calls to `soundManager.addSoundGenerator`.  11 of those specify `categoryName: 'user-interface'`, while the other 19 do not specify `categoryName`.   Is that correct?

It might be worth adding something about `categoryName` to implementation-notes.md.

**Comment by matthew-blackman** [comment]
Sound category names have been updated. @samreid and I did not feel that the Interval Tool was not part of the 'user-interface' category, since it is on the field as opposed to being in the UI layer. 

We did not feel that further documentation was needed in this sim, since the categoryName is used in tambo and has no sim-specific implementation. Closing.
