### ISSUE TITLE
Preliminary PhET-iO review-ish check-in

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-data-lab#27]
Kathy reminded us of the recommendation from the Sept 7, 2023 PhET-iO meeting to schedule early/regular check-ins regarding in-development PhET-iO software. She recommended we reach out to Chris M.

**Comment by samreid** [comment]
Here are the notes from the Sept 7, 2023 PhET-iO meeting.

CM: Until all new development includes PhET-iO… How can PhET ensure that developers are creating code that is adaptable to PhET-iO, rather than creating more code that will need to be retrofitted/rewritten in the future?
MK: We need to get all devs on a PhET-iO sim stat.

Options: 
* Always have someone with PhET-iO experience partnering on the sim
* Or have active code-review every few days … 
* Devs - AV, JG (also a11y overlap), JO (phet-io group and capsule needs deeper understanding), JB (wants deeper / more understanding)
* Be open to calling early reviews 

Do PhET-iO design – even if the sim won’t implement PhET-iO 
* Identify what should be static and what should be dynamic (from the beginning re architecture of the sim)
* At least to a certain level of design - expectations about static vs dynamic, special in terms of features that would be phet-io only 
* Fleshing out examples doc … in phet-io design aspects

@matthew-blackman said he would reach out to @pixelzoom to schedule a synchronous zoom check-in.

**Comment by matthew-blackman** [comment]
To discuss 1/8/24:

- [ ] Overview of sim behavior
- [ ] implementation-notes.md
- [ ] Fields and projectiles
- [ ] Sampling fields

**Comment by samreid** [comment]
Add a `Field` suffix to the tandems for the sampling screen.

**Comment by pixelzoom** [comment]
@matthew-blackman @samreid and I had a synchronous check-in on the implementation of this sim.  It's looking very nice, and I don't have any implementation concerns at this point.  I especially like the way that they have avoided dynamic elements by using data-type serialization for projectiles (ProjectileIO) and handling the serialization in Field (FieldIO `airborneProjectiles` and `landedProjectiles`).  I plan to appropriate this approach for the electrons in FEL.

I'm going to followup this meeting by spending up to 1 hour looking at the code, since a little asynchronous time. To be completed the week of Jan 15.

While I don't have any implementation concerns, I'm not in a position to know whether there are any design concerns. For example, are there things that are anticiapted in the Studio Tree that are missing, or cannot be added because of the implementation approach.  So for the same reason as having an early review by a PhET-iO developer, I think it would be useful (in general) to have an early review by a designer -- ideally as soon as the Studio Tree is fleshed out enough to give the feel for what elements exist and how they are organized.

**Comment by pixelzoom** [comment]
> ... I'm going to followup this meeting by spending up to 1 hour looking at the code ...

I did a quick (30-min) skim of the source code.  It's looking very nice, no concerns at this time.

**Comment by samreid** [comment]
Thanks, we will follow the recommendation for studio tree review in #30. Closing.
