### ISSUE TITLE
Launching doesn't resume after pressing Eraser button on Sampling Screen

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/projectile-data-lab#289]
**Test device**
MacBook Air M1 chip

**Operating System**
14.4.1

**Browser**
Safari and FF

**Problem description**
For https://github.com/phetsims/qa/issues/1068, on the Sampling Screen, if the Eraser button is pressed while the sim is continuously launching, the Launch Button is still in 'play mode' but no projectiles are being launched. 

**Steps to reproduce**
1. On the Sampling Screen, select Continuous mode
2. Press the Launch button
3. Press the Erase button

**Visuals**

https://github.com/phetsims/projectile-data-lab/assets/87318828/765b826b-3832-413f-aa6a-d1abc462f997

**Comment by catherinecarter** [comment]
@samreid, @matthew-blackman, and I discussed the desired behavior for the erase button on the Sampling screen. A summary of our discussion:
- It was proposed that since the Sampling screen is different than the other screens, that the eraser should also act as a "stop" button to pause data being collected
- It was proposed to have the eraser behave like the other screens by clearing the field but continue launching

Our decision was that consistency is important. Therefore, the decision is to have the erase button behave like the other screens:
- If the user is in single launch mode (i.e. no projectiles are auto-launching) and presses the eraser, the field and histogram clears, the button remains in single launch mode
- If the user is in continuous launch mode (i.e. projectiles are auto-launching) and presses the eraser, the field and histogram clears, and the button remains in continuous mode, hence projectiles continue to come out

**Comment by Nancy-Salpepi** [comment]
@samreid @matthew-blackman this doesn't appear to be fixed. If I follow the same steps as in my original comment, I get the same result as in the video.

**Comment by matthew-blackman** [comment]
Sorry for the false alarm! @samreid and I worked on this and fixed the behavior in the latest commit. It should be ready to test now.

**Comment by Nancy-Salpepi** [comment]
Looks good to me on main!

**Comment by matthew-blackman** [comment]
We also tested this with @catherinecarter and all looks well. The commits above are ready to cherry-pick.

**Comment by matthew-blackman** [comment]
Please close after verifying.

**Comment by KatieWoe** [comment]
Looks good in rc.2
