### ISSUE TITLE
Preferences controls should be changed to phetioFeatured: true

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-data-lab#308]
@matthew-blackman and I discovered there are some preferences controls that are not phetioFeatured: true. We feel that was an oversight and want to correct it.

**Comment by matthew-blackman** [comment]
Please close after verifying.

**Comment by KatieWoe** [comment]
This doesn't look fixed. The visibility property is featured, but the preference control itself isn't.

https://github.com/phetsims/projectile-data-lab/assets/41024075/ffc9d1e3-14dc-4424-bf3c-134ff5a3edf1

**Comment by matthew-blackman** [comment]
Sorry for the miscommunication in the title of this issue. @samreid and I feel that it is fine to leave the control unfeatured as long as its visible property is featured, since it will then show up if Phet-IO Elements: Featured is selected. @samreid and I confirmed in the RC that every element is auto-selectable, and every control appears in the featured tree. Therefore we feel that this issue can be closed.
