### ISSUE TITLE
[CODAP] Choosing a 'new' data table leads to no data collection

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/projectile-data-lab#343]
For https://github.com/phetsims/qa/issues/1096, if I close the Projectile Data Table and then select "new"  in the Table Menu, no data will be collected. Maybe "new" shouldn't be a choice here?

<img width="1294" alt="Screenshot 2024-06-18 at 12 37 43 PM" src="https://github.com/phetsims/projectile-data-lab/assets/87318828/ae43d5cf-91d1-4138-bfb2-832485ae2ec8">

**Comment by Nancy-Salpepi** [comment]
Also, why would be have the delete option for the Projectile Data Lab table?
<img width="235" alt="Screenshot 2024-06-20 at 3 20 46 PM" src="https://github.com/phetsims/projectile-data-lab/assets/87318828/6b8b3c93-a431-4880-92ee-82716798de7a">

**Comment by matthew-blackman** [comment]
Unfortunately there is no way to do this with the CODAP API other than setting up a complicated workaround where the table is manually rebuilt after being deleted. I set it up so that data table itself can cannot be closed, but there is no way to remove the trash can icon from the 'Tables' dropdown. I think the chances of a student going into that dropdown to delete the table are low, but if they did that they would need to reload the page.

Since this is a limitation of CODAP, there's not much more to do here. Closing.
