### ISSUE TITLE
[CODAP] console errors when checking variables while in continuous mode

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/projectile-data-lab#346]
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari 17.5

**Problem description**
For https://github.com/phetsims/qa/issues/1099, if I check  and uncheck variables while data is being collected I get an Unhandled Promise Rejection error in the console. 

**Steps to reproduce**
1. With Console open in PSD select a sample size of 15
2. Select continuous mode
3. Press Launch button
4. Check and uncheck variables

**Visuals**
<img width="540" alt="Screenshot 2024-06-20 at 2 44 17 PM" src="https://github.com/phetsims/projectile-data-lab/assets/87318828/ad117ae3-bfc8-4b77-a02d-dc40e24a975c">

**Comment by samreid** [comment]
@matthew-blackman and I investigated and found that CODAP has a 2000ms timeout in this code: https://github.com/phetsims/phet-io-sim-specific/blob/f4af064e9eb502c1763f046b39bb33f19c59413a/repos/projectile-data-lab/wrappers/codap/dependencies/iframe-phone-1.3.1.js#L205-L215

So when 500+ actions are being sent, or when the user tabs away for more than 2 seconds, we trigger this error. For the part that updates hundreds of projectiles in the table, we do not need the return value and we believe CODAP will correctly process it in time (there is no indication of the timeout interrupting any of the processes in CODAP). So it could be safe to ignore.

We discussed these strategies:
* Boost the timeout threshold
* Batch the commands so each one is <2000ms
* Ignore the problem since it is likely a safe symptom since CODAP is not left in an inconsistent state and we do not need the return value.

**Comment by Nancy-Salpepi** [comment]
For rc.1, I still see errors in the console but they don't seem to be affecting the usability of CODAP. 
<img width="504" alt="Screenshot 2024-10-21 at 4 34 31 PM" src="https://github.com/user-attachments/assets/647fe71b-25a2-4b47-bd1b-d9f141b0eb53">


I'm going to go ahead and close this (as advised by @matthew-blackman during our kickoff meeting). I will reopen if something comes up.
