### ISSUE TITLE
'Case index' is not needed

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#351]
Since the recent updates to the CODAP wrapper, 'Case Index' is no longer required to prevent the wrapper from crashing if all other attributes are deleted. Discussing this with Bill, he showed me that `caseIndex` is always available in CODAP for create column formulas, using the variable shown in the dropdown below.

![Screen Shot 2024-07-17 at 10 29 33 AM](https://github.com/user-attachments/assets/3b384863-6fe9-43d9-b995-23276b05d1d4)

Removing the duplicate 'Case Index' column would be nice to clean up the CODAP data table, since it is already shown as 'index' and available in the formula creator. @catherinecarter can you confirm that this is sufficient and that the built-in CODAP version of `caseIndex` will work for cases like tracking SD and SE versus # of projectiles?

**Comment by catherinecarter** [comment]
The caseIndex definitely works with formulas quite nicely. It's easy to find and use.

What I found is that the caseIndex cannot be a variable on the x- or y- axis in a graph. In order to investigate the Law of Large Numbers, for example, the projectile number needs to be one of the variables on the graph. So, I had to create a column with the "edit formula" entry to be the caseIndex. Not a huge lift for a user, but I essentially had to create the column we're removing in order to use it on a graph.

Some ideas (thoughts?): 
- Idea 1: Rather than removing the column, let's rename it to be "projectile number" and put it in the checkbox-list of available variables to use when collecting data (maybe at the top under Screen Identifier?), 
   - This seems logical since it is data that's being tracked in the sim but is currently unavailable in CODAP, except to create a new column and use caseIndex (although I like that I can customize the naming of the column.
   -    <img width="167" alt="image" src="https://github.com/user-attachments/assets/7078f591-8c0b-4361-a796-70d1e10bb45d">
   - A con is that if someone doesn't check the box right away, then logically the column would not start at 1, but that would be ok with me.
- Idea 2: Rename it as Projectile Number and have it as a standing column always there so there aren't gaps in numbering.
- Idea 3: Delete it and if anyone wants it, they can create a column and call it whatever they'd like (like Projectile Number)

I don't have a strong opinion about which option is best, but I do feel it's worth noting that the embedded caseIndex can't be used as a variable on a graph axis.

**Comment by matthew-blackman** [comment]
Thanks for pointing that out @catherinecarter. Let's go with option 3. I don't like the idea of introducing a variable called 'projectile number' that can easily go out of sync with the field sign, which would happen if there were multiple fields or screens being used. In the cases where a graph needs to include the number of data values, it's easy to set up a column using `caseIndex` as the formula. This is also consistent with the way it would be done in the other CODAP examples.

Feel free to reopen for discussion or if something changes down the line. Closing.
