### ISSUE TITLE
Interval tool touch area

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#47]
In a student interview, @catherinecarter noted that the student had some trouble grabbing the handles of the interval tool. Let's increase the touch area so that it is easier to grab.

**Comment by samreid** [comment]
If I recall the request, it was to have the touch area extend down to y=0 so that grabbing the line would also work.

**Comment by catherinecarter** [comment]
I'm not sure it needs to go all the way to zero, since that would be in the middle of the projectiles, and students might think they're trying to move a projectile. If it's easier, the touch area could go to the top edge of the field? 
The request was to increase the touch area, but how far down it goes wasn't specified. So whatever makes sense will probably be fine.

**Comment by matthew-blackman** [comment]
#70 has been closed and we have decided to keep the interval tool. Let's proceed with this work.

**Comment by samreid** [comment]
OK I extended the touch/mouse areas vertically:

![image](https://github.com/phetsims/projectile-data-lab/assets/679486/1f9a0f1c-3869-4865-b463-bbfad1c60a85)

@matthew-blackman or @catherinecarter want to adjust/refine/review?

**Comment by catherinecarter** [comment]
Looks great and works very well. Thanks, @samreid!

**Comment by matthew-blackman** [comment]
Everything feels great here. @samreid and I removed the tiny bit of excess touch area padding, and slightly expanded the touch area vertically to encompass the full height of the tool. We felt that horizontal padding was not needed for the handles based on their size. Closing.
