### ISSUE TITLE
Add a global hotkey for hitting the launch button without changing focus

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-data-lab#61]

**Comment by samreid** [comment]
I wrote to @terracoda in slack:

> What key or key combination should we use as a global hotkey to launch a projectile in Projectile Data Lab?

**Comment by samreid** [comment]
Should the keyboard help description differ from screen to screen? Like screen 1 says "Press (key or key combination) to launch a projectile" whereas Screen 4 says "Press (key or key combination) to launch a sample".  Or should we use the same phrase on both screens, like "Press (key or key combination) to launch" or maybe "Press (key or key combination) to launch a projectile or sample".

**Comment by samreid** [comment]
Current patch, I'll reassign to @terracoda for feedback before I can make more progress.

<details>

```diff

Subject: [PATCH] Update keyboard focus order, see https://github.com/phetsims/projectile-data-lab/issues/60
---
Index: js/variability/view/VariabilityKeyboardHelpNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/variability/view/VariabilityKeyboardHelpNode.ts b/js/variability/view/VariabilityKeyboardHelpNode.ts
--- a/js/variability/view/VariabilityKeyboardHelpNode.ts	(revision 30d1f5f44672ade61bc3be9db848aa7ffa3c09c4)
+++ b/js/variability/view/VariabilityKeyboardHelpNode.ts	(date 1704897093988)
@@ -8,12 +8,11 @@
 
 import PDLKeyboardHelpNode from '../../common/view/PDLKeyboardHelpNode.js';
 import projectileDataLab from '../../projectileDataLab.js';
-import KeyboardShortcutsHelpSection from '../../common-vsm/view/KeyboardShortcutsHelpSection.js';
 
 export default class VariabilityKeyboardHelpNode extends PDLKeyboardHelpNode {
 
   public constructor() {
-    super( new KeyboardShortcutsHelpSection() );
+    super();
   }
 }
 
Index: js/common/view/PDLKeyboardHelpNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/PDLKeyboardHelpNode.ts b/js/common/view/PDLKeyboardHelpNode.ts
--- a/js/common/view/PDLKeyboardHelpNode.ts	(revision 30d1f5f44672ade61bc3be9db848aa7ffa3c09c4)
+++ b/js/common/view/PDLKeyboardHelpNode.ts	(date 1704896999815)
@@ -12,6 +12,7 @@
 import projectileDataLab from '../../projectileDataLab.js';
 import MoveDraggableItemsKeyboardHelpSection from '../../../../scenery-phet/js/keyboard/help/MoveDraggableItemsKeyboardHelpSection.js';
 import KeyboardHelpSection from '../../../../scenery-phet/js/keyboard/help/KeyboardHelpSection.js';
+import KeyboardShortcutsHelpSection from '../../common-vsm/view/KeyboardShortcutsHelpSection.js';
 
 export default class PDLKeyboardHelpNode extends TwoColumnKeyboardHelpContent {
   public constructor( ...additionalSections: KeyboardHelpSection[] ) {
@@ -20,6 +21,7 @@
       withCheckboxContent: true
     } ) ], [
       new MoveDraggableItemsKeyboardHelpSection(),
+      new KeyboardShortcutsHelpSection(),
       ...additionalSections
     ] );
   }
Index: js/measures/view/MeasuresKeyboardHelpNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/measures/view/MeasuresKeyboardHelpNode.ts b/js/measures/view/MeasuresKeyboardHelpNode.ts
--- a/js/measures/view/MeasuresKeyboardHelpNode.ts	(revision 30d1f5f44672ade61bc3be9db848aa7ffa3c09c4)
+++ b/js/measures/view/MeasuresKeyboardHelpNode.ts	(date 1704897093991)
@@ -8,12 +8,11 @@
 
 import PDLKeyboardHelpNode from '../../common/view/PDLKeyboardHelpNode.js';
 import projectileDataLab from '../../projectileDataLab.js';
-import KeyboardShortcutsHelpSection from '../../common-vsm/view/KeyboardShortcutsHelpSection.js';
 
 export default class MeasuresKeyboardHelpNode extends PDLKeyboardHelpNode {
 
   public constructor() {
-    super( new KeyboardShortcutsHelpSection() );
+    super();
   }
 }
 
Index: js/common/view/PDLScreenView.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/PDLScreenView.ts b/js/common/view/PDLScreenView.ts
--- a/js/common/view/PDLScreenView.ts	(revision 30d1f5f44672ade61bc3be9db848aa7ffa3c09c4)
+++ b/js/common/view/PDLScreenView.ts	(date 1704895753813)
@@ -11,7 +11,7 @@
 import { EmptySelfOptions } from '../../../../phet-core/js/optionize.js';
 import projectileDataLab from '../../projectileDataLab.js';
 import ResetAllButton from '../../../../scenery-phet/js/buttons/ResetAllButton.js';
-import { HBox, Image, Node, Rectangle, Text } from '../../../../scenery/js/imports.js';
+import { HBox, Image, KeyboardListener, Node, Rectangle, Text } from '../../../../scenery/js/imports.js';
 import PDLConstants from '../PDLConstants.js';
 import ProjectileDataLabStrings from '../../ProjectileDataLabStrings.js';
 import PDLColors from '../PDLColors.js';
@@ -172,6 +172,15 @@
       }
     } );
 
+    // a listener that selects a field based on the keystroke, regardless of where focus is in the document
+    this.launchButton.addInputListener( new KeyboardListener( {
+      keys: [ 'space' ] as const,
+      global: true,
+      callback: () => {
+        model.launchButtonPressed();
+      }
+    } ) );
+
     const radioButtonLabelMaxWidth = 120;
     this.launchControlRadioButtonGroup = new VerticalAquaRadioButtonGroup( model.launchModeProperty, [ {
       value: 'single' as const,
Index: js/common-vsm/view/KeyboardShortcutsHelpSection.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common-vsm/view/KeyboardShortcutsHelpSection.ts b/js/common-vsm/view/KeyboardShortcutsHelpSection.ts
--- a/js/common-vsm/view/KeyboardShortcutsHelpSection.ts	(revision 30d1f5f44672ade61bc3be9db848aa7ffa3c09c4)
+++ b/js/common-vsm/view/KeyboardShortcutsHelpSection.ts	(date 1704897109982)
@@ -17,9 +17,10 @@
 
   public constructor() {
 
-    const row = KeyboardHelpSectionRow.createKeysRow( [ TextKeyNode.altOrOption(), KeyboardHelpIconFactory.iconToIcon( new NumberKeyNode( 0 ), new NumberKeyNode( 8 ) ) ], ProjectileDataLabStrings.selectAFieldStringProperty );
+    // const row = KeyboardHelpSectionRow.createKeysRow( [ TextKeyNode.altOrOption(), KeyboardHelpIconFactory.iconToIcon( new NumberKeyNode( 0 ), new NumberKeyNode( 8 ) ) ], ProjectileDataLabStrings.selectAFieldStringProperty );
+    const spacebarLaunchRow = KeyboardHelpSectionRow.createKeysRow( [ TextKeyNode.space() ], 'Launch a projectile or sample' );
 
-    super( ProjectileDataLabStrings.keyboardShortcutsStringProperty, [ row ], {
+    super( ProjectileDataLabStrings.keyboardShortcutsStringProperty, [ spacebarLaunchRow ], {
       textMaxWidth: 250,
       isDisposable: false // See https://github.com/phetsims/fourier-making-waves/issues/236
     } );
Index: js/sources/view/SourcesKeyboardHelpNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/sources/view/SourcesKeyboardHelpNode.ts b/js/sources/view/SourcesKeyboardHelpNode.ts
--- a/js/sources/view/SourcesKeyboardHelpNode.ts	(revision 30d1f5f44672ade61bc3be9db848aa7ffa3c09c4)
+++ b/js/sources/view/SourcesKeyboardHelpNode.ts	(date 1704897093997)
@@ -8,12 +8,11 @@
 
 import PDLKeyboardHelpNode from '../../common/view/PDLKeyboardHelpNode.js';
 import projectileDataLab from '../../projectileDataLab.js';
-import KeyboardShortcutsHelpSection from '../../common-vsm/view/KeyboardShortcutsHelpSection.js';
 
 export default class SourcesKeyboardHelpNode extends PDLKeyboardHelpNode {
 
   public constructor() {
-    super( new KeyboardShortcutsHelpSection() );
+    super();
   }
 }
 

```

</details>

**Comment by terracoda** [comment]
@samreid, I haven't looked at the sim yet. I can do that later today. Here's some general advice that I also shared on slack.

You want to keep things as general as possible - if you can. 

For example, if the shortcut is the same on each screen, will a phrase like this work, “Launch projectile or projectiles [key combination]“?

**Comment by terracoda** [comment]
I am going to check with @jessegreenberg to see if we have a list of shortcuts somewhere? Because if we don't we need to start one!!!
I am assuming this would be a sim-specific "global" hot key, but available in common code some how as I know there is at least one other sim with this cannon idea.

Being very English centric...my first guess for a shortcut that follows the broader global pattern, would be: 
- Launch projectile or projectiles [Alt] + [L] 
BUT Alt + L is already a global shortcut for the Timing Controls in MAL, and possibly other sims.

![Screenshot 2024-01-10 at 15 23 26](https://github.com/phetsims/projectile-data-lab/assets/1902116/817dae75-fc03-4ae9-b5e2-e7ce0c49a9fb)

I wonder if these other English-centric ideas would work? These follow the idea we started with BASE - 2 letter keys, the first a modifier key. This idea came from [Sashs Maximova](https://sashika.medium.com/j-k-or-how-to-choose-keyboard-shortcuts-for-web-applications-a7c3b7b408ee), and I thin it works really well for PhET sims.
- Launch Projectile [L]+[P]
- Fire Projectile from Launcher [F] + [P]

**Note:** F and J are home keys on the keyboard that make them easy to find. L an P are super close together which is handy.

If you want a shortcut to jump to the launch button, another good alternative, I think the following shortcut would follow what we have done in other sims. 
- Jump to Launcher [J] + [L] 

**Other Notes from Terracoda**
- Everything is a keyboard shortcut, so no need to repeat that heading for the field shortcut. It will need a good name. 
    - "Choose Field", "Compare Fields", "View Field" [1-8]

We have many examples for laying out KB dialogs, so it would be good to review a few, and ask questions. There were many iterations for CAV. Maybe we can avoid obvious issues with layout by deciding early on what you might think might need to be in the dialog. You don't have to do everything, but you want to consider any interactive objects or controls that are essential for learning, but not covered by Basic Actions.
 
Here's a complex dialog from Geometric Options: Basics, that can be used as an example. There are as many examples as there are sims with Alt Input, a growing number thanks to everyone's efforts.
![Screenshot 2024-01-10 at 14 39 53](https://github.com/phetsims/projectile-data-lab/assets/1902116/58d364e1-b109-48af-a887-aed28a3b0daf)
It has a custom J key that jumps through important points. Just as a warning, a single letter key shortcut like that is great for most users, especially those with dexterity limitations, but it won't work with a screen reader enabled as screen readers monopolize most keys including almost every letter key for their own shortcuts. If this sim ever gets Interactive Description, that shortcut would need to change. We worked around this issue in BASE by using the J-key as a modifier key, JS, JW, JN, and JC each respectively jump the grabbed balloon to near the **S**weater, the **W**all, **N**ear the wall, and to the **C**enter of the Play Area.

Here's Screen 1 of Ratio and Proportion. It has a 0-9 shortcut for the Both Hands interaction - requires focus on the Both Hands interaction.
![Screenshot 2024-01-10 at 14 47 30](https://github.com/phetsims/projectile-data-lab/assets/1902116/60cd060d-3039-4694-989b-2d7ff0470534)

Here's Quad's Keyboard Shortcuts with has shortcuts specific to the Voicing feature. These use the more typical modifier keys, Option for Mac, and likely ALT for Windows.
![Screenshot 2024-01-10 at 14 51 35](https://github.com/phetsims/projectile-data-lab/assets/1902116/790246e3-b9ec-44eb-9a73-ca4de1052c84)

**Comment by terracoda** [comment]
Oh, and re @matthew-blackman 's comment, the KB Shortcut dialog should just contain any necessary shortcuts for the screen - not the entire sim.

Good examples are the 2-screem sim Ratio and Proportion. Screen 1 is above. Here's screen 2:
![Screenshot 2024-01-10 at 15 57 31](https://github.com/phetsims/projectile-data-lab/assets/1902116/9f31290d-7f48-419c-87d4-783f11580f90)

And you may not need to describe every complex interaction. You can consider how one screen can scaffold the use of certain controls on a 2nd or 3rd screen. I think we did that in RaP for the combobox. We only explained that combobox interaction on screen 1.

**Comment by terracoda** [comment]
I asked @jessegreenberg on slack if we can generate a list of shortcuts already implemented.

**Comment by terracoda** [comment]
From JG on slack re other hotkeys:
> Related issue from early 2023: https://github.com/phetsims/phet-info/issues/211
> 
> Work on an automated way to detect overlap in hotkeys also started in https://github.com/phetsims/scenery/issues/1445, but we decided to put a hold on it to work on KeyboardListener instead. We could revisit that as well, although it turned out to be a tough problem to solve.
> 
> We could definitely do a code search for currently used keyboard commands.

Good that we can search for the hotkeys!

**Comment by samreid** [comment]
I investigated:

* Using shift + spacebar, but found that still triggered actions when the focus was on other components
* Describing the action based on whether it was in single or continuous mode, but that was very verbose and overly complex.

Based on those considerations, I opted for alt+L and "Press the launch button" on all 4 screens. It is working well in my testing.  Some more TODOs listed in the code before we are ready for review/testing.

**Comment by samreid** [comment]
Pushed. Ready for design review (@terracoda) and dev review (@matthew-blackman).  Happy to do either of those reviews synchronously over zoom at your discretion.

**Comment by matthew-blackman** [comment]
The code looks great - nice work! No changes recommended at this time.

@terracoda this is ready for design review. @samreid and I also have a few questions for you:

1) How would 'alt+L' work in a keyboard that is using a different alphabet? We are using 'L' for 'launch', but we are curious if there are best-practices to follow here re: localization.
2) Should we factor out the launch hotkey to be the same for the first 3 screen and the sampling screen? Right now they can be different, but we have them all set as 'alt+L' at the moment.

**Comment by terracoda** [comment]
> 1) How would 'alt+L' work in a keyboard that is using a different alphabet? We are using 'L' for 'launch', but we are curious if there are best-practices to follow here re: localization.
- I think this might be a hardware question. Keyboards can be mapped. I don't have expertise here, so I can't answer this. French keyboards have their own layout, bu they still have a letter 'L', so assuming it would work. If there is no letter 'L', I don't know what would work by default.

> 2) Should we factor out the launch hotkey to be the same for the first 3 screen and the sampling screen? Right now they can be different, but we have them all set as 'alt+L' at the moment.

I would assume you want to use the same hot key to do the same thing on each screen, BUT, does this sim have a Timing Control Node? ALT + L is already used for something in Timing Controls. I mentioned this at the top of https://github.com/phetsims/projectile-data-lab/issues/61#issuecomment-1885537673 which is why I made some other suggestions.

I still need to have direct look.

**Comment by terracoda** [comment]
@samreid the ALT + L, shortcut does launches projectiles nicely. It also overrides the Pause/Play button, and so does activating the Launcher button, so maybe that's intentional?

Also the toggle for Pause/Play is ALT + K, not ALT + L. The second shortcut is for the Step through button when paused, and this sim does not seem to use that part of the Timing Controls Node.

I'm not sure if using ALT + L in this sim should be avoided or not. There's no conflict at the moment. 

If it is important to avoid ALT + L (needs a broader discussion here with @jessegreenberg), F + L might be a nice alternative. F is a home key, and it could be thought of as "Fire Launcher" in English.

We do not yet have some general standards for creating sim-speciifc and/pr global shortcuts and ideas on how to create consistencies and avoid conflicts.

**Comment by terracoda** [comment]
I do like that you can launch a projectile from anywhere.

**Comment by terracoda** [comment]
I can quickly load up different samples on the different fields or make configuration changes and immediately try out the configuration.

**Comment by matthew-blackman** [comment]
This issue sounds like it can be closed. Nice work! Feel free to reopen if you feel otherwise.
