### ISSUE TITLE
Double check the bin calculations

### ISSUE THREAD

**Issue by samreid** [phetsims/projectile-data-lab#90]
From a TODO:

```ts
      // Calculate the bin for this value
      // TODO: Is this how you want to calculate the bin? See https://github.com/phetsims/projectile-data-lab/issues/25
      const bin = Math.floor( projectile.x / binWidth ) * binWidth;
```

**Comment by matthew-blackman** [comment]
From Slack:

@matthew-blackman: In #90, what would be a better way to do the binning? Is there some lodash magic we can use?

@samreid: #90 is not questioning the implementation strategy, but more about the rounding/logic. Like, it looks like 49.9999 would go into the 49.5 bin instead of the 50 bin, when the bin width is 0.5. Is that as desired?

@matthew-blackman: That appears correct to me, since we’d want the first bin to be 0-0.5 in that case. But I see how we are identifying the bin based the lower bound of the bin, whereas we could just be using the index. If we want the bin index (i.e., a zero-based count of which bin the value falls into), we can just use Math.floor(projectile.x / binWidth). What do you think?

@samreid: I see. We could do that, and track the bin index. But then we would later need to multiply by binWidth in const x = this.chartTransform.modelToViewX( bin );. Either way seems equally good to me.  Perhaps the bin value (instead of index) is slightly easier for debugging?

I agree with @samreid's reasoning. Removed TODO and added a small bit of documentation. Closing.
