### ISSUE TITLE
Stopwatch design

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/projectile-data-lab#94]
During an interview, a student turned on the Stopwatch right away and did not notice that there were launch controls, since the stopwatch replaced. This led to challenges using the sim, since they thought that they needed to time each launch, and didn't know about Continuous mode.

To improve the UX, let's pull out the stopwatch into a classic StopwatchNode with a 'Single launch' button, as shown below:
<img width="172" alt="Screen Shot 2024-01-19 at 12 42 14 PM" src="https://github.com/phetsims/projectile-data-lab/assets/108756567/20e59e53-e19a-437f-b68a-d2167f77e0cd">

**Comment by matthew-blackman** [comment]
To clarify the UX:

- The updated Stopwatch should not affect the overall launch UX of the sim. 
- The launch button in the stopwatch should be disabled while the timer is running.
- The launch button in the stopwatch should be disabled if the maximum number of projectiles have been launched on the current field.
- The launch button in the stopwatch will always launch a single projectile and start the timer.
- The 'Play' button should become a 'Pause' when the timer is running.

**Comment by samreid** [comment]
Note that @matthew-blackman and I have avoided phet-io/tandem changes in this area until we know the design.

**Comment by matthew-blackman** [comment]
From design meeting 1/25 with @kathy-phet @catherinecarter @ariel-phet @arouinfar and @samreid 
- It is is a priority to avoid hiding other controls when the stopwatch is visible. For this reason, we want to pursue a floating design for the stopwatch
- Using the stopwatch in Continuous mode is not a productive action, so we'd like to minimize the tendency for a user to do this.
- We want to preserve the idea that the stopwatch is a physical tool with reaction time uncertainty like a real stopwatch.
- Having a UI that is fully visible on the tool will make the intended UX more clear at a glance, as opposed to hiding UI controls in buttons with multiple states.

**Comment by samreid** [comment]
I converted the simulation to use StopwatchNode, and it seems very nice so far. Some reflections:

* The StopwatchNode is not designed or implemented in a way that allows adding additional components to its panel. This would be a significant amount of work to change.
* It surprisingly felt natural to use the stopwatch in Continuous mode, but it required me keeping track of one projectile. So I think this meets the learning goals, but based on design discussions, it seems we should add a convenient way to measure a single projectile.
* You can measure a single one by pausing the sim, pressing "go" on the stopwatch, then pressing launch. But this is awkward. (Difficult to discover, difficult to use).

Given these considerations, here are some options for how to make the "single" measurement more convenient
* Add a launch button into the stopwatch panel. As mentioned above, this is not supported and would be a significant amount of work.
* Add a launch button "nearby" the stopwatch panel (follows it around). This would be less work but less ideal UI.
* Make it so that the normal "launch" button automatically starts the stopwatch (when the stopwatch is showing).  This could be confusing or surprising or difficult to find without instructions.
* Make it so the stopwatch "start" button automatically launches a projectile. This could be difficult to discover without instructions.

**Comment by samreid** [comment]
@matthew-blackman and I implemented the proposal from the previous design meeting.

**Comment by matthew-blackman** [comment]
The behavior here feels really good to me. Timing a launch is very straightforward. The only somewhat odd behavior is when the user launches from the stopwatch during a Continuous stream. However, the current behavior is straightforward despite being a less-than-useful action for students to take. 

I'd like to review with @ariel-phet and @arouinfar before closing.

**Comment by ariel-phet** [comment]
I cannot say I am the biggest fan of this particular UX. 

1. My initial temptation is to hit the "play" button on the stopwatch
2. If I learn how to use the "Launch" from the stopwatch first, and then go to continuous mode, and then launch from the stopwatch before launching from the cannon, I might be a bit confused as to what is different about continuous mode.
3. the "play" button on the stopwatch doesn't really seem to have any obvious usefulness in the sim to me. Sure it acts as a regular stopwatch would, but do we really need it? It seems like this control could really be a single button that goes "launch" changes to a "stop" and then changes back to a "launch". I don't see another obvious use for the timer in the sim besides timing a single launch, so the multiple buttons on the stopwatch strike me as redundant. Like why use the reset to zero, if it is automatically going to do that on launch.

I am not saying not to use this tool, but wanted to clearly note some concerns with it.

**Comment by arouinfar** [comment]
This is my favorite iteration of the Stopwatch thus far. The UX still has some rough edges, but I think it's a reasonable compromise. The behavior of the Launch button is easy to explain -- it launches a single projectile and restarts the timer. It's also distinctly different from the Launch button by the field. I also like that it's simple. There's no special mode the user needs to opt into before using the synchronized launch functionality.

I agree that using the Stopwatch's "Launch" button is a bit awkward in continuous mode, but I don't think it's a particularly realistic use case. Measuring time-of-flight in continuous mode isn't productive, but disabling the Stopwatch would be poorer UX.

**Comment by catherinecarter** [comment]
I like the stopwatch being separate from the Launch button to ensure the user sees (and can still use) the Continuous mode. However, I share some concerns listed above.

I agree with @ariel-phet about the play button having no meaningful use. I also agree with both @ariel-phet and @arouinfar that continuous mode is a bit awkward due to pressing a button called, "Launch," only fires one projectile, but pressing a button with an icon (that's meant to mean the same thing as "Launch") fires many projectiles. 

That said, every time I pressed the "Launch" button on the stopwatch, I kept pressing the same button (launch) to try and stop the timer, only to have another projectile launch instead of the timer stopping. I initially searched for a "stop" button anywhere, but didn't see one. Then, I figured out I had to pause the timer instead of stop the timer. Then, I had to press a third button to reset the sim (or so I thought, until I noticed the Launch button does the same thing). 

I'd love to hear what others think about why a user would want to pause the stopwatch, and then want to press 'play' again to make the timer continue? I can't think of a reason, but that doesn't mean a reason doesn't exist. 

I personally find the interaction on the stopwatch confusing. I also find it awkward to engage with the stopwatch on continuous mode, but feel that the confusing interaction of the stopwatch is a higher concern.

**Comment by samreid** [comment]
From yesterday's design meeting:

KP: would be fine getting rid of the play/pause and reset button
Is the word, “Launch” there to distinguish it from the icon?
SR: Tried an icon, but it looked really bad and not clear. Also, stopWatchNode is in common code and currently doesn’t have any support for customizing the stopwatch
AR: can you set the visible property to false as the default? A PhET-iO client might want to have them appeared 
KP: could you just set the state to ‘false’ for the sim, so we could have them not shown? The container is dynamic and should shrink if we hide them
AR: we might have uninstrumented those buttons, or maybe we never instrumented them at all

### Decision

Take out the play/pause and reset timer button and keep the “Launch” button to launch+reset timer. Upon launch, the button changes to “Stop,” freezes the time and changes back to “Launch”

**Comment by samreid** [comment]
@matthew-blackman and I implemented it, and created a common code issue to request code review at the appropriate time.  Closing.
